### ISSUE TITLE
cannot load snap-patents dataset

### ISSUE THREAD

**Issue by minwang-ai** [CUAI/Non-Homophily-Benchmarks#2]
Hi,

Thank you for your contribution about the datasets!
I tried to run your predefined experiments directly but get the following errors when I run `bash experiments/mixhop_exp.sh snap-patents`:

`Namespace(dataset='snap-patents', sub_dataset='', hidden_channels=8, dropout=0.5, lr=0.01, method='mixhop', epochs=500, cpu=False, weight_decay=0.001, display_step=25, hops=2, num_layers=2, runs=5, cached=False, gat_heads=8, lp_alpha=0.1, gpr_alpha=0.1, directed=True, jk_type='max', rocauc=False, num_mlp_layers=1, print_prop=False, train_prop=0.5, valid_prop=0.25, rand_split=False, no_bn=False)
Traceback (most recent call last):
  File "/home/niepert-adm/Downloads/Non-Homophily-Benchmarks/main.py", line 32, in <module>
    dataset = load_nc_dataset(args.dataset, args.sub_dataset)
  File "/home/niepert-adm/Downloads/Non-Homophily-Benchmarks/dataset.py", line 102, in load_nc_dataset
    dataset = load_snap_patents_mat()
  File "/home/niepert-adm/Downloads/Non-Homophily-Benchmarks/dataset.py", line 256, in load_snap_patents_mat
    fulldata = scipy.io.loadmat(f'{DATAPATH}snap_patents.mat')
  File "/home/niepert-adm/miniconda3/envs/non-hom/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/niepert-adm/miniconda3/envs/non-hom/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/niepert-adm/miniconda3/envs/non-hom/lib/python3.9/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 32, 99
`

`bash experiments/mixhop_exp.sh twitch-e DE` works !

Best,
Min

**Comment by Xiuyu-Li** [comment]
This issue is relevant to https://github.com/CUAI/Non-Homophily-Large-Scale/issues/5, as gdd Python API cannot handle large files now. You can download `snap-patents` with the link https://drive.google.com/file/d/1ldh23TSY1PwXia6dU0MYcpyEgX-w3Hia/view?usp=sharing and put it under the `data/` directory (or wherever you would like to put the dataset).

**Comment by Xiuyu-Li** [comment]
Closing the issue for now. Let me know if this doesn't resolve it.
